### ISSUE TITLE
Source Release is incomplete

### ISSUE THREAD

**Issue by fire-eggs** [RadAd/RadImgViewer#1]
The source release is incomplete and cannot be loaded by Visual Studio. The RadWin32 folder is empty and must be explicitly downloaded from the RadWin32 repo.

**Comment by RadAd** [comment]
You need to use clone the submodules as well. ie use the --recurse-submodules option

**Comment by fire-eggs** [comment]
Thanks for the tip! However, the source package in releases is incomplete as well.

**Comment by RadAd** [comment]
I didn't create that. That is a problem with github.

**Comment by fire-eggs** [comment]
D'oh! (Smacks forehead) You're right, I forgot about that!

Sorry for wasting your time ...
